version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=vot_web_app
      - DATABASE_USER=vasko
      - DATABASE_PASSWORD=vasko_123

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: vot_web_app
      POSTGRES_USER: vasko
      POSTGRES_PASSWORD: vasko_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: